# my_bot/config/slam_toolbox_params.yaml

slam_toolbox:
  ros__parameters:
    # Simülasyon zamanını (Gazebo /use_sim_time) kullan
    use_sim_time: true

    # LIDAR verisi yayınlanan topic
    scan_topic: scan

    # Harita güncelleme aralığı (saniye)
    map_update_interval: 0.5

    # Harita çözünürlüğü (metre)
    resolution: 0.05

    # Haritanın başlangıç boyutu (metre cinsinden)
    max_laser_range: 30.0

    # Loop closure parametreleri
    loop_closure_threshold: 0.2
    loop_closure_max_dist: 3.0

    # Diğer ince ayarlar için:
    # https://github.com/SteveMacenski/slam_toolbox/blob/humble/config/mapper_params_online_async.yaml
